name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

  workflow_dispatch:

jobs:
  test-on-macos:
    name: Test on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Lint
        run: swiftlint

      - name: Build and test
        run: swift test --enable-code-coverage
  
  test-on-ios:
    name: Test on iOS
    runs-on: macos-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      
      - name: Build and test
        run: xcodebuild -scheme UKPoliceData -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.4' test
  
  test-on-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    container:
      image: swift:5.3
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and test
        run: swift test --enable-test-discovery

  danger: 
    name: "Run Danger"
    runs-on: macos-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v1

      - name: Install tools
        run: brew install danger/tap/danger-swift

      - name: Danger
        run: danger-swift ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
